import Head from 'next/head';

export default function AboutMe() {
  return (
    <>
      <Head>
        <title>Sukyungdev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      about me
    </>
  );
}
