import Head from 'next/head';
import Layout from '../component/layout';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Sukyungdev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">hi</h1>
    </Layout>
  );
}
