import Axios from 'axios';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Intro from '../components/indexComponent/Intro';
import ProjectList from '../components/ProjectList';

export default function Home() {
  const [projectData, setProjectData] = useState([]);
  const API_URL = '/api/projects';

  const getProjectData = async () => {
    let projectListData = await Axios.get(API_URL);
    console.log(projectListData.data);
    setProjectData(projectListData.data);
  };

  useEffect(() => {
    getProjectData();
  }, []);

  return (
    <div>
      <Head>
        <title>Sukyungdev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex min-h-screen flex-col text-gray-600 body-font">
        <div className="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
          <Intro />
        </div>
        <ProjectList projectData={projectData} />
      </section>
    </div>
  );
}
